### ISSUE TITLE
Set Background of Page without using body?

### ISSUE THREAD

**Issue by nicholas-richardson** [BlackrockDigital/startbootstrap-sb-admin#34]
I have a few different pages that I would like to have a different background image on. For the main page I was able to change it by applying css changes to sb-admin.css directly to the body tag. However, this then causes the same background to be used across all pages. I have tried adding a wrapper onto my other pages to add a new background image with no success and using the css from other component pages (Typescript project) to override the body with new styling but still no success.

Any suggestions would be greatly appreciated!

**Comment by nicholas-richardson** [comment]
Was able to apply background per page by wrapping the content in a div and applying the following css.

```css
.customBackground {
    display:block;
    position:absolute;
    top:0;
    left:0;
    width:100%;
    height:100%;
    background: url("assets/img/bg.jpg") no-repeat center center fixed; 
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
}
```
